### ISSUE TITLE
How to insert or delete new rule ?

### ISSUE THREAD

**Issue by tigranbs** [gdm85/go-libiptc#1]
Hi
I saw your code and it looks pretty, but I couldn't figure out how to insert new rule using it.

Can you please bring me some small example ?

Thanks

**Comment by gdm85** [comment]
@tigran-bayburtsyan sorry but I am not currently developing this library, although the code to add new rules is there I stopped testing/developing it because you'd need an easy interface to provide the "masks" for each rule. That Go interface is currently missing

**Comment by tigranbs** [comment]
Ok thanks.
I'll try to find different way of doing that.
